namespace ExceptionQuiz01
{
    internal class Program
    {
        static void Method(int size) 
        {
            int[] arr = new int[5] { 1, 2, 3, 4, 5 };

            
                for (int i = 0; i < size; i++)
                {
                    Console.WriteLine(arr[i] + " ");
                }
                Console.WriteLine();
                Console.WriteLine("정상종료");
        }
        static void Main(string[] args)
        {
            
                Console.WriteLine("입력 : ");
                int size = int.Parse(Console.ReadLine());
                try
                {
                    Method(size);
            }
            catch (Exception ex) 
            {
                Console.WriteLine("예외 발생");
                Console.WriteLine("안전 종료");
                Environment.Exit(0);
            }



        }
    }
}
